export const aboutConfig = {
  name: 'Haard Solanki',
  description:
    "I'm a backend and blockchain engineer. Currently founding engineer at Elcara, building agentic systems and market infrastructure. Also core engineer at WhiteBeard, shipping trading infrastructure and risk management systems.",
  skills: [
    'Rust',
    'TypeScript',
    'Solidity',
    'Node.js',
    'React',
    'Next.js',
    'Python',
    'Express',
    'Fastify',
    'PostgreSQL',
    'Redis',
    'MongoDB',
    'Prisma',
    'Docker',
    'Kubernetes',
    'AWS',
    'Ethers.js',
    'Anchor',
    'DeFi Protocols',
    'WebSocket',
    'AMQP',
    'CI/CD',
    'Tailwind CSS',
    'Git',
  ],
};
